"""add title to vacancy

Revision ID: 553f705546c6
Revises: 4e1d175ddc79
Create Date: 2025-08-31 18:37:28.032374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553f705546c6'
down_revision: Union[str, Sequence[str], None] = '4e1d175ddc79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('vacancies', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('vacancies', 'title')
    # ### end Alembic commands ###
